version: "3.3"

services:

  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:80
    volumes:
      - db-admin:/var/lib/pgadmin
    networks:
      - db
 
networks:
  db:
    driver: bridge

volumes:
  db-data:
  db-admin: